Repository GewoonRene/yourownpizza, pull requests merged in 2020-01, with the labels that each got.

#18 Created directory structure (closes #17)
  lib/View/Entry.dart
  lib/main.dart
Labels: Android, IOS, new feature

#24 Fixed Typo in README.md
  README.md
Labels: documentation

#27 Feature/pizza bottom
  android/gradle.properties
  lib/View/Entry.dart
  lib/View/helpers/constants.dart
  lib/View/pizza/pizzabottom.dart
  pubspec.lock
Labels: Android, IOS, new feature

#26 Entry view
  lib/View/Entry.dart
  lib/View/Shared/Bottombar.dart
Labels: Android, IOS, new feature

#34 Feature/bottomsheet
  lib/View/Shared/Bottombar.dart
Labels: Android, IOS, new feature

#41 'Feature/dranken' merge to 'master'
  lib/View/Entry.dart
  lib/View/Shared/Bottombar.dart
  lib/View/drinks/drinks.dart
  lib/View/drinks/helpers/DrinkManager.dart
  lib/View/drinks/helpers/DrinksData.dart
  lib/View/drinks/widgets/DrinkTile.dart
  lib/View/helpers/Buttons.dart
  lib/View/helpers/constants.dart
  lib/View/pizza/pizzabottom.dart
  lib/View/pizza/pizzacrust.dart
  lib/View/sideDishes/starters.dart
  lib/main.dart
Labels: Android, IOS, new feature

#43 Feature/ingredienten
  lib/View/drinks/widgets/DrinkTile.dart
  lib/View/ingredients/helpers/IngredientsData.dart
  lib/View/ingredients/ingredients.dart
  lib/View/pizza/pizzacrust.dart
Labels: Android, IOS, new feature

#44 Test/unit tests
  LICENSE.md
  README.md
  test/drinks/DrinkTile.test.dart
  test/helpers/buttons.test.dart
  test/main.test.dart
  test/widget_test.dart
Labels: Android, IOS, documentation, new feature

#46 Add Drink and back button
  lib/View/drinks/drinks.dart
  lib/View/ingredients/ingredients.dart
  lib/View/pizza/pizzabottom.dart
  lib/View/pizza/pizzacrust.dart
  lib/View/sideDishes/starters.dart
Labels: Android, IOS, design

#47 Database setup
  .gitignore
  android/app/build.gradle
  android/build.gradle
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/GoogleService-Info.plist
  lib/View/Shared/Bottombar.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: new feature

#48 Feature/desserts
  lib/View/Entry.dart
  lib/View/Shared/Bottombar.dart
  lib/View/desserts/desserts.dart
  lib/View/ingredients/ingredients.dart
  lib/main.dart
Labels: Android, Bugfix, IOS, new feature
